import { supabase } from './supabase';
import type { PlayerFormData } from '../types';

export const squadData: PlayerFormData[] = [
  { nombre: 'Mateo', apellidos: 'Altamira', demarcacion: 'Delantero', talla: 1.84, partidos_jugados: 28, titularidades: 24, minutos_jugados: 2150, goles: 18, asistencias: 5, tarjetas_amarillas: 3, tarjetas_rojas: 0, dorsal: 9, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Mateo Altamira' },
  { nombre: 'Lucas', apellidos: 'Benavídez', demarcacion: 'Centrocampista', talla: 1.76, partidos_jugados: 30, titularidades: 29, minutos_jugados: 2540, goles: 6, asistencias: 12, tarjetas_amarillas: 4, tarjetas_rojas: 1, dorsal: 8, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Lucas Benavídez' },
  { nombre: 'Santiago', apellidos: 'Kross', demarcacion: 'Defensa', talla: 1.89, partidos_jugados: 27, titularidades: 24, minutos_jugados: 2430, goles: 2, asistencias: 1, tarjetas_amarillas: 7, tarjetas_rojas: 2, dorsal: 4, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Santiago Kross' },
  { nombre: 'Diego', apellidos: 'Villanova', demarcacion: 'Portero', talla: 1.92, partidos_jugados: 31, titularidades: 31, minutos_jugados: 2790, goles: 0, asistencias: 0, tarjetas_amarillas: 1, tarjetas_rojas: 0, dorsal: 1, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Diego Villanova' },
  { nombre: 'Enzo', apellidos: 'Rossi', demarcacion: 'Delantero', talla: 1.80, partidos_jugados: 15, titularidades: 8, minutos_jugados: 780, goles: 5, asistencias: 2, tarjetas_amarillas: 2, tarjetas_rojas: 0, dorsal: 11, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Enzo Rossi' },
  { nombre: 'Julián', apellidos: 'Valenzuela', demarcacion: 'Centrocampista', talla: 1.72, partidos_jugados: 32, titularidades: 32, minutos_jugados: 2810, goles: 4, asistencias: 9, tarjetas_amarillas: 5, tarjetas_rojas: 0, dorsal: 6, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Julián Valenzuela' },
  { nombre: 'Thiago', apellidos: 'Montenegro', demarcacion: 'Defensa', talla: 1.85, partidos_jugados: 26, titularidades: 23, minutos_jugados: 2010, goles: 1, asistencias: 3, tarjetas_amarillas: 6, tarjetas_rojas: 1, dorsal: 2, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Thiago Montenegro' },
  { nombre: 'Nicolás', apellidos: 'Archundia', demarcacion: 'Delantero', talla: 1.78, partidos_jugados: 29, titularidades: 26, minutos_jugados: 2210, goles: 14, asistencias: 7, tarjetas_amarillas: 2, tarjetas_rojas: 0, dorsal: 7, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Nicolás Archundia' },
  { nombre: 'Bruno', apellidos: 'Cavallaro', demarcacion: 'Centrocampista', talla: 1.81, partidos_jugados: 22, titularidades: 14, minutos_jugados: 1320, goles: 3, asistencias: 4, tarjetas_amarillas: 4, tarjetas_rojas: 0, dorsal: 14, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Bruno Cavallaro' },
  { nombre: 'Sebastián', apellidos: 'Galdames', demarcacion: 'Defensa', talla: 1.82, partidos_jugados: 29, titularidades: 28, minutos_jugados: 2480, goles: 0, asistencias: 2, tarjetas_amarillas: 8, tarjetas_rojas: 0, dorsal: 5, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Sebastián Galdames' },
  { nombre: 'Matías', apellidos: 'Pedraza', demarcacion: 'Centrocampista', talla: 1.75, partidos_jugados: 18, titularidades: 10, minutos_jugados: 950, goles: 2, asistencias: 5, tarjetas_amarillas: 1, tarjetas_rojas: 0, dorsal: 10, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Matías Pedraza' },
  { nombre: 'Joaquín', apellidos: 'Forlán', demarcacion: 'Delantero', talla: 1.87, partidos_jugados: 31, titularidades: 30, minutos_jugados: 2620, goles: 22, asistencias: 4, tarjetas_amarillas: 3, tarjetas_rojas: 1, dorsal: 19, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Joaquín Forlán' },
  { nombre: 'Rodrigo', apellidos: 'Castromán', demarcacion: 'Defensa', talla: 1.88, partidos_jugados: 30, titularidades: 30, minutos_jugados: 2700, goles: 3, asistencias: 0, tarjetas_amarillas: 5, tarjetas_rojas: 0, dorsal: 3, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Rodrigo Castromán' },
  { nombre: 'Gabriel', apellidos: 'Santoro', demarcacion: 'Portero', talla: 1.90, partidos_jugados: 33, titularidades: 2, minutos_jugados: 70, goles: 0, asistencias: 0, tarjetas_amarillas: 0, tarjetas_rojas: 0, dorsal: 12, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Gabriel Santoro' },
  { nombre: 'Tomás', apellidos: 'Quintanilla', demarcacion: 'Centrocampista', talla: 1.70, partidos_jugados: 25, titularidades: 18, minutos_jugados: 1640, goles: 5, asistencias: 6, tarjetas_amarillas: 2, tarjetas_rojas: 0, dorsal: 16, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Tomás Quintanilla' },
  { nombre: 'Alejandro', apellidos: 'Fontes', demarcacion: 'Defensa', talla: 1.83, partidos_jugados: 14, titularidades: 9, minutos_jugados: 890, goles: 1, asistencias: 1, tarjetas_amarillas: 4, tarjetas_rojas: 1, dorsal: 15, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Alejandro Fontes' },
  { nombre: 'Iker', apellidos: 'Zabaleta', demarcacion: 'Centrocampista', talla: 1.79, partidos_jugados: 27, titularidades: 25, minutos_jugados: 2180, goles: 7, asistencias: 8, tarjetas_amarillas: 3, tarjetas_rojas: 0, dorsal: 21, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Iker Zabaleta' },
  { nombre: 'Facundo', apellidos: 'Mendieta', demarcacion: 'Delantero', talla: 1.82, partidos_jugados: 20, titularidades: 11, minutos_jugados: 1050, goles: 6, asistencias: 3, tarjetas_amarillas: 1, tarjetas_rojas: 0, dorsal: 20, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Facundo Mendieta' },
  { nombre: 'Gonzalo', apellidos: 'Barreto', demarcacion: 'Defensa', talla: 1.86, partidos_jugados: 31, titularidades: 31, minutos_jugados: 2750, goles: 2, asistencias: 2, tarjetas_amarillas: 9, tarjetas_rojas: 2, dorsal: 22, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Gonzalo Barreto' },
  { nombre: 'Samuel', apellidos: 'Albizuri', demarcacion: 'Centrocampista', talla: 1.74, partidos_jugados: 12, titularidades: 4, minutos_jugados: 420, goles: 1, asistencias: 1, tarjetas_amarillas: 0, tarjetas_rojas: 0, dorsal: 18, lateralidad: 'Diestro', equipo: 'AD TeamManager', fecha_nacimiento: '2000-01-01', apodo: 'Samuel Albizuri' },
];

export async function bulkImportPlayers() {
  const { error } = await supabase.from('jugadores').insert(squadData);
  
  if (error) {
    console.error('Error in bulk import:', error);
    throw error;
  }
}
